# Generated by Django 5.1.6 on 2025-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                default="Не указано",
                max_length=128,
                null=True,
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                default="Не указано",
                max_length=128,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                default="Не указано",
                max_length=128,
                null=True,
                verbose_name="Имя пользователя",
            ),
        ),
    ]
