services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recommendation_system_network

  redis:
    image: redis:latest
    networks:
      - recommendation_system_network

  recommendation_system:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "poetry run python manage.py collectstatic --noinput && poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/recommendation_system
      - static_volume:/recommendation_system/staticfiles
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${USER}:${PASSWORD}@postgres:${PORT}/${NAME}
    depends_on:
      - postgres
      - redis
    networks:
      - recommendation_system_network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/nginx/staticfiles
    depends_on:
      - recommendation_system
    networks:
      - recommendation_system_network

networks:
  recommendation_system_network:

volumes:
  postgres_data:
  static_volume: