[tool.poetry]
name = "recommendation-system"
version = "0.1.0"
description = ""
authors = ["Sti_ll@mail.ru"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
